package com.cscotta.portlandintlbeerfest;

public class BeerDBSQL {

	// SQL Statement to prepare the database.
	public static String[] POPULATE_DB = 
		{"CREATE TABLE beer (_id integer PRIMARY KEY autoincrement, name text, beer_type text, style text, abv text, ibu integer, country text, serving text, favorite integer, description text, link text);",
		"INSERT INTO beer VALUES(1,'16th Anniversary Double IPA','Ale','Double (Imperial) IPA','10.0%', 80,'USA','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(6,'A Little Sumpin Sumpin Ale','Ale','NEW WORLD-USA','8.7%',72,'USA','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(7,'Amager Batch One','Ale','Barley Wine','9.2%',80,'Denmark','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(8,'Amager Imperial Stout','Ale','Imperial stout-Countries vary','10.0%',99,'Denmark','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(9,'Amber Grand Imperial Porter','Lager','Porter-Baltic','8.0%',30,'Poland','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(10,'Amber Kozlak Bock Beer','Lager','Bock-Germany','6.5%',22,'Poland','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(11,'Anniversary Double IPA','Ale','Double (Imperial) IPA','8.7%',99,'USA','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(12,'Anthem Cherry Cider','Cider','Cider (Hard, Apple or Pear)','6.2%',0,'USA','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(13,'Ayinger Brau Weisse','Ale','Hefe Weizen-Germany','5.1%',13,'Germany','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(14,'Baird Angry Boy Brown Ale','Ale','Brown Ales-England','6.2%',72,'Japan','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(15,'Batemans Mr. Georges Ruby Porter','Ale','Porter-England','5.0%',48,'England','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(16,'Big Foot (Vintage 2009)','Ale','Barley Wine','9.6%',90,'USA','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(17,'Black Boss','Lager','Porter-Baltic','9.4%',32,' Poland','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(18,'Black Butte XXII','Ale','Imperial Porter (countries vary)','11.0%',95,'USA','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(19,'Bockor Bellegems Bruin','Ale','Flemish/Flanders Red-Belgium',' 6.0%',15,'Belgium','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(20,'Bourbon 300','Ale','Strong Ale (American)','8.0%',45,'USA','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(23,'Brew Free or Die IPA','Ale','India Pale Ale (IPA)-England','7.0%',70,'USA','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(24,'Brother Davids Double','Ale','Dubbel-Belgium','9.0%',27,'USA','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(25,'Caldera Hopportunity Knocks','Ale','Strong Ale (American)','6.8%',70,'USA','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(26,'Caldera IPA','Ale','India Pale Ale (IPA)-England','6.1%',65,'USA','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(27,'Caldera Pale','Ale','Pale Ale-USA','5.6%',48,'USA','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(28,'Cantillon Iris','Ale','Lambic-Belgium','5.0%',10,'Belgium','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(29,'Cantillon Lou Pepe Pure Kriek','Ale','Lambic-Fruit-Belgium','5.0%',10,'Belgium','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(30,'Charlevoix Dominus Vobiscum','Ale','Dubbel-Belgium','9.0%',10,' Canada','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(31,'Chatoe Rogue OREgasmic','Ale','NEW WORLD-USA','6.0%',80,'USA','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(32,'Chocolate Oak-Aged Yeti','Ale','Imperial stout-Countries vary','9.5%',75,'USA','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(33,'Christoffel Nobel','Lager','Strong Lager / Malt Liquor','8.7%',18,'Belgium','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(34,'Cranberry Spice Mead','Mead','Mead','12.0%',0,'USA','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(35,'Crispin Honey Crisp','Cider','Cider (Hard, Apple or Pear)','6.5%',0,'USA','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(36,'De la Senne Equinox','Ale','Strong Ale (Blonde/Pale)-Belgium','8.0%',30,'Belgium','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(37,'De Molen Hel & Verdoemenis','Ale','Imperial stout-Countries vary','11.0%',25,' Holland','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(38,'De Proef K-O','Ale','Strong Ale (Blonde/Pale)-Belgium','10.0%',35,'Belgium','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(43,'Amber Grand Imperial Porter','Lager','Porter-Baltic','8.0%',30,'Poland','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(55,'Bourbon Barrel Aged Dopplebock','Lager','Doppelbock-Germany','8.0%',30,'USA','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(56,'Bourbon Barrel Mystery Beer','Ale','Wood-aged Specialty','10.0%',50,'USA','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(58,'Brother Davids Double','Ale','Dubbel-Belgium','9.0%',27,'USA','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(73,'De Ranke Cuvée De Ranke','Ale','Lambic-Belgium','7.0%',15,'Belgium','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(74,'De Ranke XX Bitter','Ale','Strong Golden-Belgium','9.0%',55,'Belgium','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(75,'Deadlift','Ale','Double (Imperial) IPA','8.6%',70,'USA','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(76,'DeuS (Brut Methode Champagnoise)','Ale','Strong Ale (Blonde/Pale)-Belgium','11.5%',20,'Belgium','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(77,'Devils Kriek','Ale','Fruit (non Lambic)-Countries vary','9.0%',35,'USA','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(78,'Dicks Tripel','Ale','Tripel-Belgium','9.0%',20,'usa','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(79,'Dieu du Ciel! Peche Mortel Stout','Ale','Imperial stout-Countries vary','9.5%',40,'Canada','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(80,'Dieu du Ciel! Rigor Mortis Abt','Ale','Quadrupel-Belgium','10.5%',15,'Canada','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(81,'Double Jack','Ale','Double (Imperial) IPA','9.5%',99,'USA','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(82,'Double Trouble','Ale','Double (Imperial) IPA','9.2%',99,'USA','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(83,'Drie Fonteinen Schaerbeekse Kriek','Ale','Lambic-Fruit-Belgium','6.0%',10,'Belgium','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(84,'Dupont Saison','Ale','Saison-Belgium','6.5%',33,'Belgium','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(85,'Duvel','Ale','Strong Golden-Belgium','8.5%',18,'Belgium','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(86,'Ephémère (Apple)','Ale','Hybrid: see beer description','5.5%',16,'Canada','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(87,'Epic Armageddon IPA','Ale','India Pale Ale (IPA)-England','6.7%',50,'New Zealand','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(88,'Epic Mayhem','Ale','Strong Ale (American)','6.2%',40,'New Zealand','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(89,'Firestone Walker Parabola','Ale','Imperial stout-Countries vary','11.0%',50,'USA','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(90,'Franziskaner Dunkel Hefe-Weisse','Ale','Dunkel Weizen-Germany','5.0%',14,'Germany','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(91,'Franziskaner Hefe-Weisse','Ale','Hefe Weizen-Germany','5.0%',14,'Germany','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(92,'Göller Maerzen','Lager','Ur-Marzen or Oktoberfest- Germany','5.5%',28,'','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(93,'Haandbryggeriet Odins Tipple','Ale','Imperial stout-Countries vary','11.0%',45,'Norway','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(94,'Hell or High Watermelon Wheat','Ale','Fruit (non Lambic)-Countries vary','5.5%',20,'USA','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(95,'High Road Scotch','Ale','Scotch Ale-Scotland','9.3%',18,'USA','Draft', 0, '', '');",
		"INSERT INTO beer VALUES(96,'Hop Stoopid','Ale','Double (Imperial) IPA','9.0%',99,'usa','Bottle', 0, '', '');",
		"INSERT INTO beer VALUES(97,'Ise Kadoya Triple Hop Ale','Ale','Pale Ale-USA','5.0%',35,'Japan','Bottle', 0, '', '');",
		};

}