package com.cscotta.portlandintlbeerfest;

public class BeerDBSQL {

	// SQL Statement to prepare the database.
	public static String[] POPULATE_DB = 
		{"CREATE TABLE beer (_id integer PRIMARY KEY autoincrement, name, beer_type, style, abv, ibu, country, serving);",
		"INSERT INTO beer VALUES(1,'16th Anniversary Wood-Aged Double IPA','Ale','Double (Imperial) IPA',' 10.0%',' 80',' USA',' Draft');",
		"INSERT INTO beer VALUES(2,'16th Anniversary Wood-Aged Double IPA','Ale','Double (Imperial) IPA',' 10.0%',' 80',' USA',' Draft');",
		"INSERT INTO beer VALUES(3,'16th Anniversary Wood-Aged Double IPA','Ale','Double (Imperial) IPA',' 10.0%',' 80',' USA',' Draft');",
		"INSERT INTO beer VALUES(4,'16th Anniversary Wood-Aged Double IPA','Ale','Double (Imperial) IPA',' 10.0%',' 80',' USA',' Draft');",
		"INSERT INTO beer VALUES(5,'16th Anniversary Wood-Aged Double IPA','Ale','Double (Imperial) IPA',' 10.0%',' 80',' USA',' Draft');",
		"INSERT INTO beer VALUES(6,'A Little Sumpin'' Sumpin'' Ale','Ale','NEW WORLD-USA',' 8.7%',' 72',' USA',' Draft');",
		"INSERT INTO beer VALUES(7,'Amager Batch One','Ale','Barley Wine',' 9.2%',' 80',' Denmark',' Bottle');",
		"INSERT INTO beer VALUES(8,'Amager Imperial Stout','Ale','Imperial stout-Countries vary',' 10.0%',' 99',' Denmark',' Draft');",
		"INSERT INTO beer VALUES(9,'Amber Grand Imperial Porter','Lager','Porter-Baltic',' 8.0%',' 30',' Poland',' Bottle');",
		"INSERT INTO beer VALUES(10,'Amber Kozlak Bock Beer','Lager','Bock-Germany',' 6.5%',' 22',' Poland',' Bottle');",
		"INSERT INTO beer VALUES(11,'Anniversary Double IPA','Ale','Double (Imperial) IPA',' 8.7%',' 99',' USA',' Draft');",
		"INSERT INTO beer VALUES(12,'Anthem Cherry Cider','Cider','Cider (Hard, Apple or Pear)',' 6.2%',' 0',' USA',' Draft');",
		"INSERT INTO beer VALUES(13,'Ayinger Brau Weisse','Ale','Hefe Weizen-Germany',' 5.1%',' 13',' Germany',' Draft');",
		"INSERT INTO beer VALUES(14,'Baird Angry Boy Brown Ale','Ale','Brown Ales-England',' 6.2%',' 72',' Japan',' Bottle');",
		"INSERT INTO beer VALUES(15,'Batemans Mr. George''s Ruby Porter','Ale','Porter-England',' 5.0%',' 48',' England',' Bottle');",
		"INSERT INTO beer VALUES(16,'Big Foot (Vintage 2009)','Ale','Barley Wine',' 9.6%',' 90',' USA',' Draft');",
		"INSERT INTO beer VALUES(17,'Black Boss','Lager','Porter-Baltic',' 9.4%',' 32',' Poland',' Bottle');",
		"INSERT INTO beer VALUES(18,'Black Butte XXII','Ale','Imperial Porter (countries vary)',' 11.0%',' 95',' USA',' Draft');",
		"INSERT INTO beer VALUES(19,'Bockor Bellegems Bruin','Ale','Flemish/Flanders Red-Belgium',' 6.0%',' 15',' Belgium',' Draft');",
		"INSERT INTO beer VALUES(20,'Bourbon 300','Ale','Strong Ale (American)',' 8.0%',' 45',' USA',' Draft');",
		"INSERT INTO beer VALUES(21,'Bourbon Barrel Aged Dopplebock','Lager','Doppelbock-Germany',' 8.0%',' 30',' USA',' Draft');",
		"INSERT INTO beer VALUES(22,'Bourbon Barrel Mystery Beer','Ale','Wood-aged Specialty',' 10.0%',' 50',' USA',' Draft');",
		"INSERT INTO beer VALUES(23,'Brew Free or Die IPA','Ale','India Pale Ale (IPA)-England',' 7.0%',' 70',' USA',' Bottle');",
		"INSERT INTO beer VALUES(24,'Brother David''s Double','Ale','Dubbel-Belgium',' 9.0%',' 27',' USA',' Draft');",
		"INSERT INTO beer VALUES(25,'Caldera Hopportunity Knocks','Ale','Strong Ale (American)',' 6.8%',' 70',' USA',' Bottle');",
		"INSERT INTO beer VALUES(26,'Caldera IPA','Ale','India Pale Ale (IPA)-England',' 6.1%',' 65',' USA',' Bottle');",
		"INSERT INTO beer VALUES(27,'Caldera Pale','Ale','Pale Ale-USA',' 5.6%',' 48',' USA',' Bottle');",
		"INSERT INTO beer VALUES(28,'Cantillon Iris','Ale','Lambic-Belgium',' 5.0%',' 10',' Belgium',' Draft');",
		"INSERT INTO beer VALUES(29,'Cantillon Lou Pepe Pure Kriek','Ale','Lambic-Fruit-Belgium',' 5.0%',' 10',' Belgium',' Bottle');",
		"INSERT INTO beer VALUES(30,'Charlevoix Dominus Vobiscum','Ale','Dubbel-Belgium',' 9.0%',' 10',' Canada',' Bottle');",
		"INSERT INTO beer VALUES(31,'Chatoe Rogue OREgasmic','Ale','NEW WORLD-USA',' 6.0%',' 80',' USA',' Draft');",
		"INSERT INTO beer VALUES(32,'Chocolate Oak-Aged Yeti','Ale','Imperial stout-Countries vary',' 9.5%',' 75',' USA',' Draft');",
		"INSERT INTO beer VALUES(33,'Christoffel Nobel','Lager','Strong Lager / Malt Liquor',' 8.7%',' 18',' Belgium',' Draft');",
		"INSERT INTO beer VALUES(34,'Cranberry Spice Mead','Mead','Mead',' 12.0%',' 0',' USA',' Bottle');",
		"INSERT INTO beer VALUES(35,'Crispin Honey Crisp','Cider','Cider (Hard, Apple or Pear)',' 6.5%',' 0',' USA',' Bottle');",
		"INSERT INTO beer VALUES(36,'De la Senne Equinox','Ale','Strong Ale (Blonde/Pale)-Belgium',' 8.0%',' 30',' Belgium',' Bottle');",
		"INSERT INTO beer VALUES(37,'De Molen Hel & Verdoemenis','Ale','Imperial stout-Countries vary',' 11.0%',' 25',' Holland',' Bottle');",
		"INSERT INTO beer VALUES(38,'De Proef K-O','Ale','Strong Ale (Blonde/Pale)-Belgium',' 10.0%',' 35',' Belgium',' Bottle');",
		"INSERT INTO beer VALUES(39,'16th Anniversary Wood-Aged Double IPA','Ale','Double (Imperial) IPA','10.0%',80,'USA','Draft');",
		"INSERT INTO beer VALUES(40,'A Little Sumpin’ Sumpin’ Ale','Ale','NEW WORLD-USA','8.7%',72,'USA','Draft');",
		"INSERT INTO beer VALUES(41,'Amager Batch One','Ale','Barley Wine','9.2%',80,'Denmark','Bottle');",
		"INSERT INTO beer VALUES(42,'Amager Imperial Stout','Ale','Imperial stout-Countries vary','10.0%',99,'Denmark','Draft');",
		"INSERT INTO beer VALUES(43,'Amber Grand Imperial Porter','Lager','Porter-Baltic','8.0%',30,'Poland','Bottle');",
		"INSERT INTO beer VALUES(44,'Amber Kozlak Bock Beer','Lager','Bock-Germany','6.5%',22,'Poland','Bottle');",
		"INSERT INTO beer VALUES(45,'Anniversary Double IPA','Ale','Double (Imperial) IPA','8.7%',99,'USA','Draft');",
		"INSERT INTO beer VALUES(46,'Anthem Cherry Cider','Cider','Cider (Hard, Apple or Pear)','6.2%',0,'USA','Draft');",
		"INSERT INTO beer VALUES(47,'Ayinger Brau Weisse','Ale','Hefe Weizen-Germany','5.1%',13,'Germany','Draft');",
		"INSERT INTO beer VALUES(48,'Baird Angry Boy Brown Ale','Ale','Brown Ales-England','6.2%',72,'Japan','Bottle');",
		"INSERT INTO beer VALUES(49,'Batemans Mr. George’s Ruby Porter','Ale','Porter-England','5.0%',48,'England','Bottle');",
		"INSERT INTO beer VALUES(50,'Big Foot (Vintage 2009)','Ale','Barley Wine','9.6%',90,'USA','Draft');",
		"INSERT INTO beer VALUES(51,'Black Boss','Lager','Porter-Baltic','9.4%',32,'Poland','Bottle');",
		"INSERT INTO beer VALUES(52,'Black Butte XXII','Ale','Imperial Porter (countries vary)','11.0%',95,'USA','Draft');",
		"INSERT INTO beer VALUES(53,'Bockor Bellegems Bruin','Ale','Flemish/Flanders Red-Belgium','6.0%',15,'Belgium','Draft');",
		"INSERT INTO beer VALUES(54,'Bourbon 300','Ale','Strong Ale (American)','8.0%',45,'USA','Draft');",
		"INSERT INTO beer VALUES(55,'Bourbon Barrel Aged Dopplebock','Lager','Doppelbock-Germany','8.0%',30,'USA','Draft');",
		"INSERT INTO beer VALUES(56,'Bourbon Barrel Mystery Beer','Ale','Wood-aged Specialty','10.0%',50,'USA','Draft');",
		"INSERT INTO beer VALUES(57,'Brew Free or Die IPA','Ale','India Pale Ale (IPA)-England','7.0%',70,'USA','Bottle');",
		"INSERT INTO beer VALUES(58,'Brother David''s Double','Ale','Dubbel-Belgium','9.0%',27,'USA','Draft');",
		"INSERT INTO beer VALUES(59,'Caldera Hopportunity Knocks','Ale','Strong Ale (American)','6.8%',70,'USA','Bottle');",
		"INSERT INTO beer VALUES(60,'Caldera IPA','Ale','India Pale Ale (IPA)-England','6.1%',65,'USA','Bottle');",
		"INSERT INTO beer VALUES(61,'Caldera Pale','Ale','Pale Ale-USA','5.6%',48,'USA','Bottle');",
		"INSERT INTO beer VALUES(62,'Cantillon Iris','Ale','Lambic-Belgium','5.0%',10,'Belgium','Draft');",
		"INSERT INTO beer VALUES(63,'Cantillon Lou Pepe Pure Kriek','Ale','Lambic-Fruit-Belgium','5.0%',10,'Belgium','Bottle');",
		"INSERT INTO beer VALUES(64,'Charlevoix Dominus Vobiscum','Ale','Dubbel-Belgium','9.0%',10,'Canada','Bottle');",
		"INSERT INTO beer VALUES(65,'Chatoe Rogue OREgasmic','Ale','NEW WORLD-USA','6.0%',80,'USA','Draft');",
		"INSERT INTO beer VALUES(66,'Chocolate Oak-Aged Yeti','Ale','Imperial stout-Countries vary','9.5%',75,'USA','Draft');",
		"INSERT INTO beer VALUES(67,'Christoffel Nobel','Lager','Strong Lager / Malt Liquor','8.7%',18,'Belgium','Draft');",
		"INSERT INTO beer VALUES(68,'Cranberry Spice Mead','Mead','Mead','12.0%',0,'USA','Bottle');",
		"INSERT INTO beer VALUES(69,'Crispin Honey Crisp','Cider','Cider (Hard, Apple or Pear)','6.5%',0,'USA','Bottle');",
		"INSERT INTO beer VALUES(70,'De la Senne Equinox','Ale','Strong Ale (Blonde/Pale)-Belgium','8.0%',30,'Belgium','Bottle');",
		"INSERT INTO beer VALUES(71,'De Molen Hel & Verdoemenis','Ale','Imperial stout-Countries vary','11.0%',25,'Holland','Bottle');",
		"INSERT INTO beer VALUES(72,'De Proef K-O','Ale','Strong Ale (Blonde/Pale)-Belgium','10.0%',35,'Belgium','Bottle');",
		"INSERT INTO beer VALUES(73,'De Ranke Cuvée De Ranke','Ale','Lambic-Belgium','7.0%',15,'Belgium','Bottle');",
		"INSERT INTO beer VALUES(74,'De Ranke XX Bitter','Ale','Strong Golden-Belgium','9.0%',55,'Belgium','Draft');",
		"INSERT INTO beer VALUES(75,'Deadlift','Ale','Double (Imperial) IPA','8.6%',70,'USA','Draft');",
		"INSERT INTO beer VALUES(76,'DeuS (Brut Methode Champagnoise)','Ale','Strong Ale (Blonde/Pale)-Belgium','11.5%',20,'Belgium','Bottle');",
		"INSERT INTO beer VALUES(77,'Devil''s Kriek','Ale','Fruit (non Lambic)-Countries vary','9.0%',35,'USA','Draft');",
		"INSERT INTO beer VALUES(78,'Dick''s Tripel','Ale','Tripel-Belgium','9.0%',20,'usa','Draft');",
		"INSERT INTO beer VALUES(79,'Dieu du Ciel! Peche Mortel Stout','Ale','Imperial stout-Countries vary','9.5%',40,'Canada','Draft');",
		"INSERT INTO beer VALUES(80,'Dieu du Ciel! Rigor Mortis Abt','Ale','Quadrupel-Belgium','10.5%',15,'Canada','Draft');",
		"INSERT INTO beer VALUES(81,'Double Jack','Ale','Double (Imperial) IPA','9.5%',99,'USA','Draft');",
		"INSERT INTO beer VALUES(82,'Double Trouble','Ale','Double (Imperial) IPA','9.2%',99,'USA','Draft');",
		"INSERT INTO beer VALUES(83,'Drie Fonteinen Schaerbeekse Kriek','Ale','Lambic-Fruit-Belgium','6.0%',10,'Belgium','Bottle');",
		"INSERT INTO beer VALUES(84,'Dupont Saison','Ale','Saison-Belgium','6.5%',33,'Belgium','Bottle');",
		"INSERT INTO beer VALUES(85,'Duvel','Ale','Strong Golden-Belgium','8.5%',18,'Belgium','Bottle');",
		"INSERT INTO beer VALUES(86,'Éphémère (Apple)','Ale','Hybrid: see beer description','5.5%',16,'Canada','Bottle');",
		"INSERT INTO beer VALUES(87,'Epic Armageddon IPA','Ale','India Pale Ale (IPA)-England','6.7%',50,'New Zealand','Bottle');",
		"INSERT INTO beer VALUES(88,'Epic Mayhem','Ale','Strong Ale (American)','6.2%',40,'New Zealand','Bottle');",
		"INSERT INTO beer VALUES(89,'Firestone Walker Parabola','Ale','Imperial stout-Countries vary','11.0%',50,'USA','Bottle');",
		"INSERT INTO beer VALUES(90,'Franziskaner Dunkel Hefe-Weisse','Ale','Dunkel Weizen-Germany','5.0%',14,'Germany','Draft');",
		"INSERT INTO beer VALUES(91,'Franziskaner Hefe-Weisse','Ale','Hefe Weizen-Germany','5.0%',14,'Germany','Draft');",
		"INSERT INTO beer VALUES(92,'Göller Maerzen','Lager','Ur-Marzen or Oktoberfest- Germany','5.5%',28,'','Draft');",
		"INSERT INTO beer VALUES(93,'Haandbryggeriet Odin''s Tipple','Ale','Imperial stout-Countries vary','11.0%',45,'Norway','Bottle');",
		"INSERT INTO beer VALUES(94,'Hell or High Watermelon Wheat','Ale','Fruit (non Lambic)-Countries vary','5.5%',20,'USA','Bottle');",
		"INSERT INTO beer VALUES(95,'High Road Scotch','Ale','Scotch Ale-Scotland','9.3%',18,'USA','Draft');",
		"INSERT INTO beer VALUES(96,'Hop Stoopid','Ale','Double (Imperial) IPA','9.0%',99,'usa','Bottle');",
		"INSERT INTO beer VALUES(97,'Ise Kadoya Triple Hop Ale','Ale','Pale Ale-USA','5.0%',35,'Japan','Bottle');",
		"INSERT INTO beer VALUES(98,'J.K.’s Scrumpy Cider','Cider','Cider (Hard, Apple or Pear)','6.0%',0,'USA','Bottle');",
		"INSERT INTO beer VALUES(99,'Jandrain-Jandrenouille IV','Ale','Saison-Belgium','6.5%',18,'Belgium','Draft');",
		"INSERT INTO beer VALUES(100,'John John Juniper Pale','Ale','NEW WORLD-USA','5.2%',34,'USA','Draft');",
		"INSERT INTO beer VALUES(101,'Kerkom Bink Bloesem','Ale','Hybrid: see beer description','7.1%',25,'Belgium','Draft');",
		"INSERT INTO beer VALUES(102,'Ketucky Überwine','Ale','Barley Wine','10.5%',35,'USA','Draft');",
		"INSERT INTO beer VALUES(103,'Klein Duimpje Erik de Noorman','Ale','Barley Wine','9.5%',30,'Holland','Bottle');",
		"INSERT INTO beer VALUES(104,'Kraken','Ale','Wood-aged Specialty','6.8%',55,'USA','Draft');",
		"INSERT INTO beer VALUES(105,'Kulmbacher Eisbock','Lager','Eisbock-Germany','9.2%',26,'Germany','Bottle');",
		"INSERT INTO beer VALUES(106,'Kulmbacher EKU Pils','Lager','Pilsner-Germany','4.9%',36,'Germany','Draft');",
		"INSERT INTO beer VALUES(107,'Kulmbacher Mönchshof Schwarzbier','Lager','Schwartzbier','4.9%',25,'Germany','Draft');",
		"INSERT INTO beer VALUES(108,'La Fin Du Monde','Ale','Tripel-Belgium','9.0%',19,'Canada','Bottle');",
		"INSERT INTO beer VALUES(109,'La Folie','Ale','Flemish/Flanders Red-Belgium','6.0%',10,'USA','Draft');",
		"INSERT INTO beer VALUES(110,'Lang-Bräu Amber Märzen','Lager','Ur-Marzen or Oktoberfest- Germany','5.5%',20,'Germany','Draft');",
		"INSERT INTO beer VALUES(111,'Lindemans Framboise','Ale','Lambic-Fruit-Belgium','4.0%',10,'Belgium','Bottle');",
		"INSERT INTO beer VALUES(112,'Lucky #13','Ale','Strong Ale (American)','8.3%',77,'USA','Bottle');",
		"INSERT INTO beer VALUES(113,'Mahr''s Hell','Lager','Helles-Germany','4.9%',20,'Germany','Draft');",
		"INSERT INTO beer VALUES(114,'Mahr''s Ungespundet','Lager','Keller Bier','4.9%',30,'Germany','Bottle');",
		"INSERT INTO beer VALUES(115,'Maiden The Shade','Ale','Strong Ale (American)','6.7%',70,'USA','Draft');",
		"INSERT INTO beer VALUES(116,'Matilda','Ale','Strong Ale (Blonde/Pale)-Belgium','7.0%',32,'USA','Draft');",
		"INSERT INTO beer VALUES(117,'Maudite','Ale','Strong Ale (Blonde/Pale)-Belgium','8.0%',22,'Canada','Draft');",
		"INSERT INTO beer VALUES(118,'Meantime Scotch Ale','Ale','Scotch Ale-Scotland','8.0%',25,'England','Bottle');",
		"INSERT INTO beer VALUES(119,'Mikkeller Beer Geek Breakfast Bacon','Ale','Imperial stout-Countries vary','10.9%',50,'Denmark','Bottle');",
		"INSERT INTO beer VALUES(120,'Mikkeller Black Hole','Ale','Imperial stout-Countries vary','13.1%',38,'Denmark','Draft');",
		"INSERT INTO beer VALUES(121,'Mikkeller Black Hole (Bourbon Barrel)','Ale','Imperial stout-Countries vary','13.1%',55,'Denmark','Bottle');",
		"INSERT INTO beer VALUES(122,'Mikkeller Simcoe Single Hop','Ale','India Pale Ale (IPA)-England','6.9%',65,'Denmark','Draft');",
		"INSERT INTO beer VALUES(123,'Molten Lava','Ale','Double (Imperial) IPA','9.0%',90,'USA','Draft');",
		"INSERT INTO beer VALUES(124,'Mystery beer #1','Ale','Wood-aged Specialty','9.0%',0,'USA','Draft');",
		"INSERT INTO beer VALUES(125,'Mystery beer #2','Ale','Wood-aged Specialty','9.0%',0,'USA','Draft');",
		"INSERT INTO beer VALUES(126,'Nectar Ales Black Xantus','Ale','Imperial stout-Countries vary','11.0%',50,'USA','Bottle');",
		"INSERT INTO beer VALUES(127,'Nøgne Ø # 100 (Batch 100)','Ale','Double (Imperial) IPA','10.0%',80,'Norway','Draft');",
		"INSERT INTO beer VALUES(128,'Nøgne-Ø Imperial Brown Ale','Ale','Strong Ale-England','7.5%',30,'Norway','Bottle');",
		"INSERT INTO beer VALUES(129,'Olde Reliable','Ale','Barley Wine','10.0%',90,'USA','Draft');",
		"INSERT INTO beer VALUES(130,'Organic Green Elephant','Ale','India Pale Ale (IPA)-England','6.9%',68,'USA','Draft');",
		"INSERT INTO beer VALUES(131,'Orval','Ale','Trappist Beers-Belgium/Netherlands','7.0%',32,'Belgium','Bottle');",
		"INSERT INTO beer VALUES(132,'Parade Belgian Pale','Ale','Pale Ale-Belgium','6.0%',40,'USA','Draft');",
		"INSERT INTO beer VALUES(133,'Peroni','Lager','Export Lager','4.7%',20,'Italy','Draft');",
		"INSERT INTO beer VALUES(134,'Pilsner Urquell','Lager','Pilsner-Czech','4.4%',30,'Czech Republic','Draft');",
		"INSERT INTO beer VALUES(135,'Premium Lager','Lager','Helles-Germany','5.2%',21,'Germany','Draft');",
		"INSERT INTO beer VALUES(136,'Primator Maibock','Lager','Helles bock/ Maibock-Germany','7.5%',34,'Czech Republic','Bottle');",
		"INSERT INTO beer VALUES(137,'Primator Premium Lager','Lager','Export Lager','5.0%',26,'Czech Republic','Bottle');",
		"INSERT INTO beer VALUES(138,'Proletariat Red','Ale','Hybrid: see beer description','6.2%',45,'USA','Draft');",
		"INSERT INTO beer VALUES(139,'Radeberger','Lager','Pilsner-Germany','4.8%',32,'Germany','Draft');",
		"INSERT INTO beer VALUES(140,'Ranger IPA','Ale','India Pale Ale (IPA)-England','6.5%',70,'USA','Draft');",
		"INSERT INTO beer VALUES(141,'Red Head Imperial IPA','Ale','Double (Imperial) IPA','8.2%',0,'usa','Draft');",
		"INSERT INTO beer VALUES(142,'Rise Up Red','Ale','Pale Ale-USA','5.8%',60,'USA','Bottle');",
		"INSERT INTO beer VALUES(143,'Rochefort 10 Trappist','Ale','Trappist Beers-Belgium/Netherlands','11.3%',26,'Belgium','Bottle');",
		"INSERT INTO beer VALUES(144,'Rose Petal Imperial Golden Ale','Ale','Hybrid: see beer description','6.7%',20,'USA','Draft');",
		"INSERT INTO beer VALUES(145,'Samuel Smith Organic Raspberry','Ale','Fruit (non Lambic)-Countries vary','5.0%',10,'England','Bottle');",
		"INSERT INTO beer VALUES(146,'Samuel Smith Yorkshire Stingo','Ale','Strong Ale-England','8.0%',35,'Belgium','Bottle');",
		"INSERT INTO beer VALUES(147,'Scaldis Prestige','Ale','Strong Ale (Blonde/Pale)-Belgium','13.0%',19,'Belgium','Bottle');",
		"INSERT INTO beer VALUES(148,'Slaapmutske Triple Nightcap','Ale','Tripel-Belgium','8.1%',40,'Belgium','Draft');",
		"INSERT INTO beer VALUES(149,'Southern Hemisphere Harvest','Ale','India Pale Ale (IPA)-England','6.7%',66,'USA','Draft');",
		"INSERT INTO beer VALUES(150,'Spaten Munich Dunkel','Lager','Munich style dunkel-Germany','5.5%',24,'Germany','Draft');",
		"INSERT INTO beer VALUES(151,'Spaten Oktoberfest (Ur-Marzen)','Lager','Ur-Marzen or Oktoberfest- Germany','5.9%',23,'Germany','Draft');",
		"INSERT INTO beer VALUES(152,'Spaten Optimator','Lager','Doppelbock-Germany','7.2%',24,'Germany','Draft');",
		"INSERT INTO beer VALUES(153,'Spaten Pils','Lager','Pilsner-Germany','5.0%',36,'Germany','Draft');",
		"INSERT INTO beer VALUES(154,'Spaten Premium Bock','Lager','Helles bock/ Maibock-Germany','6.5%',30,'Germany','Draft');",
		"INSERT INTO beer VALUES(155,'Spezial Rauchbier','Lager','Rauchbier (smoked) - Germany (Bamberg)','4.6%',34,'Germany','Draft');",
		"INSERT INTO beer VALUES(156,'St Feuillien Saison','Ale','Saison-Belgium','6.5%',26,'Belgium','Bottle');",
		"INSERT INTO beer VALUES(157,'St. Feuillien Tripel','Ale','Tripel-Belgium','8.5%',28,'Belgium','Bottle');",
		"INSERT INTO beer VALUES(158,'Sublimely Self Righteous Ale','Ale','NEW WORLD-USA','8.7%',68,'USA','Draft');",
		"INSERT INTO beer VALUES(159,'Super Jubel 2010','Ale','Winter Warmers-Countries vary','10.5%',56,'USA','Draft');",
		"INSERT INTO beer VALUES(160,'The Saint Reserve','Cider','Cider (Hard, Apple or Pear)','6.9%',0,'USA','Bottle');",
		"INSERT INTO beer VALUES(161,'Trickster''s Treat Agave Mead','Mead','Mead','13.0%',0,'USA','Bottle');",
		"INSERT INTO beer VALUES(162,'Trois Mousquetaires Imperial Weizen','Ale','Hybrid: see beer description','10.0%',20,'Canada','Bottle');",
		"INSERT INTO beer VALUES(163,'Trois Mousquetaires Rauchbier','Lager','Rauchbier (smoked) - Germany (Bamberg)','5.9%',18,'Canada','Bottle');",
		"INSERT INTO beer VALUES(164,'Tuatara Pils','Lager','Pilsner- Bohemian','5.0%',30,'New Zealand','Bottle');",
		"INSERT INTO beer VALUES(165,'Undercover Investigation Shut-Down Ale','Ale','Strong Ale (American)','9.0%',74,'USA','Draft');",
		"INSERT INTO beer VALUES(166,'Union Jack','Ale','India Pale Ale (IPA)-England','7.0%',75,'USA','Draft');",
		"INSERT INTO beer VALUES(167,'Urthel Hop-IT!','Ale','Hybrid: see beer description','9.5%',80,'Belgium','Bottle');",
		"INSERT INTO beer VALUES(168,'Velvet Underground','Ale','Strong Ale (American)','8.8%',60,'USA','Draft');",
		"INSERT INTO beer VALUES(169,'Wanderlust Cider','Cider','Cider (Hard, Apple or Pear)','8.4%',0,'USA','Draft');",
		"INSERT INTO beer VALUES(170,'Weissenohe Bonator','Lager','Doppelbock-Germany','8.2%',30,'Germany','Bottle');",
		"INSERT INTO beer VALUES(171,'Westmalle Triple','Ale','Trappist Beers-Belgium/Netherlands','9.5%',37,'Belgium','Bottle');",
		"INSERT INTO beer VALUES(172,'Workhorse IPA','Ale','India Pale Ale (IPA)-England','7.5%',80,'USA','Draft');",
		"INSERT INTO beer VALUES(173,'Zatec Dark Czech Lager','Lager','Munich style dunkel-Germany','5.6%',25,'Czech Republic','Bottle');"
		};

}